#input rgb hm + pcd voxel 
CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
BACKBONE_MODEL: '' #'pose_resnet'
MODEL: 'multi_person_posenet'
DATA_DIR: ''
GPUS: '0,1'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 2
PRINT_FREQ: 10

DATASET:
  COLOR_RGB: True
  TRAIN_DATASET: 'collection'
  TEST_DATASET: 'collection'
  DATA_FORMAT: jpg
  DATA_AUGMENTATION: False
  FLIP: False
  ROOT: /disk1/fanbohao/datasets/PointCloud/collected_datasets/ # 'data/panoptic/'
  ROOT_POSE2D: '/disk1/fanbohao/fbh_code/openpifpaf/collected_datasets'
  ROT_FACTOR: 45
  SCALE_FACTOR: 0.35
  TEST_SUBSET: 'validation'
  TRAIN_SUBSET: 'train'
  ROOTIDX:
    - 0
  CAMERA_NUM: 4
  SCALE: 1000
NETWORK:
  PRETRAINED_BACKBONE: ''
  PRETRAINED:  ''  # 'models/pytorch/imagenet/resnet50-19c8e357.pth'
  TARGET_TYPE: gaussian
  PARAMETER_IMAGE_SIZE:
  - 2048
  - 1536
  IMAGE_SIZE:
  - 2048
  - 1536
  HEATMAP_SIZE:
  - 512
  - 384
  SIGMA: 15
  NUM_JOINTS: 15
  USE_GT: False
  USE_PCD: True
  USE_RGB: True
LOSS:
  USE_TARGET_WEIGHT: true
TRAIN:
  BATCH_SIZE: 1
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 30
  RESUME: true
  OPTIMIZER: adam
  LR: 0.0001
TEST:
  MODEL_FILE: "model_best.pth.tar"
  BATCH_SIZE: 1
DEBUG:
  DEBUG: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true
MULTI_PERSON:
  SPACE_SIZE:
    - 30.4
    - 21.2
    - 2
  SPACE_CENTER:
    - 15.2 # 120.0
    - 10.6 # -600.0
    - 1
  INITIAL_CUBE_SIZE:
    - 304
    - 212
    - 20
  MAX_PEOPLE_NUM: 15
  THRESHOLD: 0.1
PICT_STRUCT:
  GRID_SIZE:
    - 2.0
    - 2.0
    - 2.0
  CUBE_SIZE:
    - 64
    - 64
    - 64
